# CS414 - Numpy Theory
Instructions: 
- Start the kernel: In the menu bar, select Kernel -> Restart kernel.
- Complete all sections with the comment `YOUR CODE HERE`.
- Run all code blocks to check the implementation: In the menu bar, select Cell -> Run All.

In [1]:
import numpy as np

## Problem 1: Vector Initialization
Initialize a vector of `n` elements, all of which are `0`.

Example:

- Input:
```
n = 5
```

- Output:
```
[0., 0., 0., 0., 0.]
```

In [2]:
def init_zeros(n):
    # YOUR CODE HERE
    return np.zeros(n)
    raise NotImplementedError()

In [3]:
# testing with an example
init_zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# grading cell 1
assert init_zeros(5).shape == (5, )
assert np.sum(abs(init_zeros(5) - np.array([0, 0, 0, 0, 0]))) == 0

In [5]:
# grading cell 2


## Problem 2: Vector Initialization
Initialize a vector of `n` elements, all of which are `1`.

Example:

- Input:
```
n = 5
```

- Output:
```
[1, 1, 1, 1, 1]
```

In [6]:
def init_ones(n):
    # YOUR CODE HERE
    return np.ones(n)
    raise NotImplementedError()

In [7]:
# testing with an example
init_ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
# grading cell 3
assert init_ones(5).shape == (5, )
assert np.sum(abs(init_ones(5) - np.array([1, 1, 1, 1, 1]))) == 0

In [9]:
# grading cell 4


## Problem 3: Vector Initialization
Initialize a vector of `n` elements, all of which are `x`.

Example:

- Input:
```
n = 5
x = 3.5
```

- Output:
```
[3.5, 3.5, 3.5, 3.5, 3.5]
```

In [10]:
def init_all_x(n, x):
    # YOUR CODE HERE
    return np.ones(n) * x
    raise NotImplementedError()

In [11]:
# testing with an example
init_all_x(5, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5])

In [12]:
# grading cell 5
assert init_all_x(5, 3.5).shape == (5, )
assert np.sum(abs(init_all_x(5, 3.5) - np.array([3.5, 3.5, 3.5, 3.5, 3.5]))) == 0

In [13]:
# grading cell 6


## Problem 4: Vector Initialization
Initialize a vector of size `n` consisting of integers increasing from `0` to `n-1`.

Example:

- Input:
```
n = 5
```

- Output:
```
[0, 1, 2, 3, 4]
```

In [14]:
def init_range(n):
    # YOUR CODE HERE
    return np.arange(n)
    raise NotImplementedError()

In [15]:
# testing with an example
init_range(5)

array([0, 1, 2, 3, 4])

In [16]:
# grading cell 7
assert init_range(5).shape == (5, )
assert np.sum(abs(init_range(5) - np.array([0,1,2,3,4]))) == 0

In [17]:
# grading cell 8


## Problem 5: Vector Initialization
Initialize a vector of size `n` consisting of integers increasing from `x, x+1, ..., x+n-1` (a sequence starting from `x`).

Example:

- Input:
```
n = 5
x = 3.5
```

- Output:
```
[3.5, 4.5, 5.5, 6.5, 7.5]
```

In [18]:
def init_range(n, x):
    # YOUR CODE HERE
    return np.array(np.ones(n) * x + np.arange(n))
    raise NotImplementedError()

In [19]:
# testing with an example
init_range(5, 3.5)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [20]:
# grading cell 9
assert init_range(5, 3).shape == (5, )
assert np.sum(abs(init_range(5, 3) - np.array([3, 4, 5, 6, 7]))) == 0

In [21]:
# grading cell 10


## Problem 6: Matrix Initialization
Initialize a matrix of size `m x n` consisting of all elements as `K`.

Example:

- Input:
```
m = 3
n = 4
K = 5
```

- Output:
```
[[5., 5., 5., 5.],
 [5., 5., 5., 5.],
 [5., 5., 5., 5.]]
```

In [22]:
def init_mat_K(m, n, K):
    # YOUR CODE HERE
    return np.ones((m, n)) * K
    raise NotImplementedError()

In [23]:
# testing with an example
init_mat_K(3, 4, 5)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
# grading cell 11
assert init_mat_K(2,3,4).shape == (2, 3)
assert np.sum(abs(init_mat_K(2,3,4) - np.array([[4, 4, 4], [4, 4, 4]]))) == 0

In [25]:
# grading cell 12


## Problem 7: Matrix Initialization
Initialize a radom matrix of size `m x n` consisting integers within a given range.

Example:

- Input:
```
m = 3
n = 4
min_val = 1
max_val = 10
```

- Output:
```
[[5, 9, 7, 2]
 [4, 3, 8, 6]
 [1, 7, 2, 9]]
```

In [26]:
def init_mat_randints(m, n, min_val, max_val):
    # YOUR CODE HERE
    return np.random.randint(min_val, max_val, (m, n))
    raise NotImplementedError()

In [27]:
# testing with an example
init_mat_randints(3, 4, 1, 10)

array([[2, 9, 4, 9],
       [7, 9, 1, 3],
       [8, 2, 1, 2]])

In [28]:
# grading cell 13
assert init_mat_randints(2, 3, 1, 10).shape == (2, 3)
assert np.all((init_mat_randints(2, 3, 1, 10) >= 1) & (init_mat_randints(2, 3, 1, 10) <= 10))

In [29]:
# grading cell 14


## Problem 8: Matrix Initialization
Initialize a matrix of size `m x n` consisting of all elements as `K` and replace all odd values in `arr` with `-1`.

Example:

- Input: 
```
[[5, 8],
 [7, 8],
 [8, 3]]
```
- Output: 
```
[[-1,  8],
 [-1,  8],
 [ 8, -1]]
```

In [30]:
def init_mat_randints(m, n, min_val, max_val):
    # YOUR CODE HERE
    return np.random.randint(min_val, max_val, (m, n))
    raise NotImplementedError()

def replace_odd_values(matrix):
    # YOUR CODE HERE
    return np.where(matrix % 2 == 1, -1, matrix)
    raise NotImplementedError()

In [31]:
# testing with an example
matrix = np.array([[5, 8], [7, 8], [8, 3]])
replace_odd_values(matrix)

array([[-1,  8],
       [-1,  8],
       [ 8, -1]])

In [32]:
# grading cell 15
matrix = replace_odd_values(init_mat_randints(4, 3, 1, 10))
assert np.array_equal(matrix, np.where(matrix % 2 != 0, -1, matrix)), "Odd values are not replaced correctly."

In [33]:
# grading cell 16


## Problem 9: Matrix Initialization
Initialize an identity matrix of a specified size.

Example:

- Input:
```
m = 5
```

- Output:
```
[[1, 0, 0, 0, 0]
 [0, 1, 0, 0, 0]
 [0, 0, 1, 0, 0]
 [0, 0, 0, 1, 0]
 [0, 0, 0, 0, 1]]
```

In [34]:
def init_mat_identity_matrix(n):
    # YOUR CODE HERE
    return np.eye(n, dtype=int)
    raise NotImplementedError()

In [35]:
# testing with an example
init_mat_identity_matrix(5)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [36]:
# grading cell 17
assert init_mat_identity_matrix(3).shape == (3, 3)
assert np.all(np.diag(init_mat_identity_matrix(3)) == 1)
assert np.all(init_mat_identity_matrix(3)[np.where(~np.eye(init_mat_identity_matrix(3).shape[0], dtype=bool))] == 0)

In [37]:
# grading cell 18


## Problem 10: Matrix Initialization
Initialize a matrix of size `m x n` with elements increasing from left to right and top to bottom. The smallest element starts from `1`.

Example:

- Input:
```
m = 2
n = 4
```

- Output:
```
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [38]:
def init_mat_increase(m, n):
    # YOUR CODE HERE
    return np.arange(1,m*n+1).reshape(m, n)
    raise NotImplementedError()

In [39]:
# testing with an example
init_mat_increase(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
# grading cell 19
assert init_mat_increase(2,3).shape == (2, 3)
assert np.sum(abs(init_mat_increase(2,3) - np.array([[1, 2, 3], [4, 5, 6]]))) == 0

In [41]:
# grading cell 20
