# CS414 - Numpy Manipulation
Instructions: 
- Start the kernel: In the menu bar, select Kernel -> Restart kernel.
- Complete all sections with the comment `YOUR CODE HERE`.
- Run all code blocks to check the implementation: In the menu bar, select Cell -> Run All.

In [72]:
import numpy as np

## Problem 1: Vector Operations
Define functions to perform vector addition, subtraction, scalar multiplication, and dot product of two vectors `a` and `b` of the same shape.

Example:

- Input:
```
a =  [1 2 3]
```
```
b =  [4 5 6]
```

- Output:
```
addition: [5 7 9]
subtraction: [-3 -3 -3]
scalar multiplication: [ 4 10 18]
dot product: 32
```

In [73]:
def vector_addition(a, b):
    # YOUR CODE HERE
    return np.add(a, b)
    raise NotImplementedError()

def vector_subtraction(a, b):
    # YOUR CODE HERE
    return np.subtract(a, b)
    raise NotImplementedError()
    

def scalar_multiplication(scalar, vector):
    # YOUR CODE HERE
    return np.multiply(scalar, vector)
    raise NotImplementedError()

def dot_product(a, b):
    # YOUR CODE HERE
    return np.dot(a, b)
    raise NotImplementedError()

In [74]:
# testing with an example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(vector_addition(a, b))
print(vector_subtraction(a, b))
print(scalar_multiplication(a, b))
print(dot_product(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
32


In [75]:
# grading cell 1
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = vector_addition(a, b)
expected = np.array([5, 7, 9])
assert np.array_equal(result, expected), "Vector addition is incorrect."

a = np.array([4, 5, 6])
b = np.array([1, 2, 3])
result = vector_subtraction(a, b)
expected = np.array([3, 3, 3])
assert np.array_equal(result, expected), "Vector subtraction is incorrect."

scalar = 2
vector = np.array([1, 2, 3])
result = scalar_multiplication(scalar, vector)
expected = np.array([2, 4, 6])

assert np.array_equal(result, expected), "Scalar multiplication is incorrect."
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = dot_product(a, b)
expected = 32
assert result == expected, "Dot product is incorrect."

In [76]:
# grading cell 2


## Problem 2: Matrix Manipulation
Define functions to  Hadamard product (element-wise product), and dot product dot product of two matrices `A` and `B` with random integers of the same shape.


Example:

- Input:
```
A =  [[7 7 7]
 [7 2 1]
 [5 1 8]]
```
```
B =  [[3 4 8]
 [3 6 2]
 [4 2 1]]
```

- Output:
```
Element-wise multiplication: [[21 28 56]
                              [21 12  2]
                              [20  2  8]]
Dot product: 170
```

In [77]:
def hadamard_product(matrix1, matrix2):
    # YOUR CODE HERE
    return np.multiply(matrix1, matrix2)
    raise NotImplementedError()

def dot_product(matrix1, matrix2):
    # YOUR CODE HERE
    return np.sum(hadamard_product(matrix1, matrix2))
    raise NotImplementedError()

In [78]:
# testing with an example
matrix1 = np.array([[7,7,7], [7,2,1], [5,1,8]])
matrix2 = np.array([[3,4,8], [3,6,2], [4,2,1]])
print(hadamard_product(matrix1, matrix2))
print(dot_product(matrix1, matrix2))

[[21 28 56]
 [21 12  2]
 [20  2  8]]
170


In [79]:
# grading cell 3
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = hadamard_product(matrix1, matrix2)
assert np.array_equal(result, np.array([[5, 12], [21, 32]])), "Hadamard product is incorrect."

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = dot_product(matrix1, matrix2)
assert result > 69, "Dot product is incorrect."

In [80]:
# grading cell 4


## Problem 3: Matrix Vector Addition
Define a function that takes two matrices `X` and `W` as input and returns the value `M` using the following formula:
```
M = 2 (X^T + W).X
```
where `X^T` represents the transpose of `X`. It is necessary to check the dimensions to ensure that the calculation can always be performed before executing the operation. Return `None` if the dimensions are incompatible.

Example:

- Input:
```
X = [[1 1]
     [0 0]]
```
```
W = [[1 1]
     [0 0]]
```

- Output:
```
[[4 4]
[2 2]]
```

In [81]:
def prod_sum_mat(x, w):
    # YOUR CODE HERE
    if(x.shape[1] != w.shape[0]):
        return None 
    
    x_transpose = np.transpose(x)
    m = np.dot(2*(np.add(x_transpose, w)),x)
    return m
    raise NotImplementedError()

In [82]:
# testing with an example
X = np.array([[1, 1], [0, 0]])
W = np.array([[1, 1], [0, 0]])
prod_sum_mat(X, W)

array([[4, 4],
       [2, 2]])

In [83]:
# grading cell 5
X = np.array([[1, 1], [2, 3], [5, 4]])
W = np.array([[1, 2, 3], [4, 5, 6]])
assert np.sum(abs(prod_sum_mat(X, W)-np.array([[100, 92], [142, 138]]))) < 0.0001

In [84]:
# grading cell 6


## Problem 4: Matrix Transpose
Define a function to compute the matrix transpose.

Example:

- Input:
```
[[2 4 6]
 [1 3 5]]
```

- Output:
```
[[2 1]
 [4 3]
 [6 5]]
```

In [85]:
def compute_transpose(matrix):
    # YOUR CODE HERE
    return np.transpose(matrix)
    raise NotImplementedError()

In [86]:
# testing with an example
compute_transpose(np.array([[2, 4, 6], [1, 3, 5]]))

array([[2, 1],
       [4, 3],
       [6, 5]])

In [87]:
# grading cell 7
matrix1 = np.random.randint(1, 10, size=(3, 4))
assert (compute_transpose(matrix1).shape == (4, 3)),  "Transposed matrix is incorrect."
assert np.array_equal(compute_transpose(matrix1), matrix1.T),  "Transposed matrix is incorrect."

In [88]:
# grading cell 8


## Problem 5: Matrix Determinant
Define a function to compute the determinant of a square matrix.

Example:

- Input:
```
[[1, 2],
 [3, 4]]
```

- Output: `-2`


In [89]:
def compute_determinant(matrix):
    # YOUR CODE HERE
    return int(np.linalg.det(matrix))
    raise NotImplementedError()

In [90]:
# testing with an example
compute_determinant(np.array([[1,2],[3,4]]))

-2

In [91]:
# grading cell 9
matrix1 = np.array([[19, 29,  7, 62], [84, 27, 89, 69], [45, 43, 13, 34], [89, 73, 78, 87]])
assert np.isclose(compute_determinant(matrix1), -3750052), "Determinant matrix is incorrect."

In [92]:
# grading rading cell 10


## Problem 6: Matrix Inversion
Define a function to find the inverse of a square matrix. If the matrix is non-invertible (singular), it returns `None`.

Example:

- Input:
```
[[7, 2, 3],
 [3, 3, 1],
 [7, 4, 5]]
```

- Output:
```
[[ 0.32352941,  0.05882353, -0.20588235],
 [-0.23529412,  0.41176471,  0.05882353],
 [-0.26470588, -0.41176471,  0.44117647]]
```

In [93]:
def find_inverse(matrix):
    # YOUR CODE HERE
    if np.linalg.det(matrix) == 0:
        return None
    return np.linalg.inv(matrix)
    raise NotImplementedError()

In [94]:
find_inverse(np.array([[7,2,3],[3,3,1],[7,4,5]]))

array([[ 0.32352941,  0.05882353, -0.20588235],
       [-0.23529412,  0.41176471,  0.05882353],
       [-0.26470588, -0.41176471,  0.44117647]])

In [95]:
# grading cell 11
matrix1 = np.array([[1, 2], [3, 4]])
assert np.allclose(find_inverse(matrix1), np.array([[-2, 1], [1.5, -0.5]])), "Invertible matrix is incorrect."

In [96]:
# grading cell 12


## Problem 7: Eigenvalues and Eigenvectors
Define functions to calculate the eigenvalues and eigenvectors of a square matrix.

Example:

- Input:
```
[[1, 2] 
 [3, 4]]
```

- Output:
```
Eigenvalues: [-0.37228132, 5.37228132]
Eigenvectors: [[-0.82456484, -0.41597356], 
               [0.56576746, -0.90937671]]
```

In [97]:
def calculate_eigenvalues(matrix):
    # YOUR CODE HERE
    return np.linalg.eigvals(matrix)
    raise NotImplementedError()

def calculate_eigenvectors(matrix):
    # YOUR CODE HERE
    return np.linalg.eig(matrix)[1]
    raise NotImplementedError()

In [98]:
# testing with an example
print(calculate_eigenvalues([[1,2],[3,4]]))
print(calculate_eigenvectors([[1,2],[3,4]]))

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [99]:
# grading cell 13
matrix = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
assert np.allclose(calculate_eigenvalues(matrix), np.array([2.76509717e+01, -6.50971698e-01,  1.12335729e-15])), "Eigenvalues of matrix are incorrect."

matrix = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
expect_res = np.array([[-0.37636677, -0.75529416,  0.40824829],
                       [-0.55798202, -0.05094566, -0.81649658],
                       [-0.73959727,  0.65340284,  0.40824829]])
assert np.allclose(calculate_eigenvectors(matrix), expect_res), "Eigenvectors of matrix are incorrect."

In [100]:
# grading cell 14


## Problem 8: Matrix Translation
Define a function to translation a square matrix. 

Example:

- Input:
```
[[1, 2] 
 [3, 4]]
```
```
[5, 6]
```
- Output:
```
[[ 6,  8]
 [ 8, 10]]
```

In [101]:
def matrix_translation(matrix, translation_vector):
    # YOUR CODE HERE
    return np.add(matrix, translation_vector)
    raise NotImplementedError()

In [102]:
# testing with an example
matrix_translation(np.array([[1,2],[3,4]]), np.array([5,6]))

array([[ 6,  8],
       [ 8, 10]])

In [103]:
# grading cell 15
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
translation_vector = np.array([2, -1, 3])
assert np.array_equal(matrix_translation(matrix, translation_vector), np.array([[3, 1, 6], [6, 4, 9], [9, 7, 12]])), "Translated matrix is incorrect."

In [104]:
# grading cell 16


## Problem 9: Matrix Rotation
Define a function to rotate a square matrix by 90 degrees clockwise. 

Example:

- Input:
```
[[1, 2] 
 [3, 4]]
```

- Output:
```
[[3, 1]
 [4, 2]]
```

In [105]:
def rotate_matrix_clockwise(matrix):
    # YOUR CODE HERE
    return np.rot90(matrix, 3)
    raise NotImplementedError()

In [106]:
# testing with an example
rotate_matrix_clockwise(np.array([[1,2],[3,4]]))

array([[3, 1],
       [4, 2]])

In [107]:
# grading cell 17
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
expected_rotated_matrix = np.array([[7, 4, 1], [8, 5, 2], [9, 6, 3]])
assert np.array_equal(rotate_matrix_clockwise(matrix), expected_rotated_matrix), "Rotated matrix function is incorrect."

In [108]:
# grading cell 18


## Problem 10: LU Decomposition
Define a function to perform LU decomposition on a square matrix. If the matrix is singular or not suitable for LU decomposition, it returns `None`.

Example:

- Input:
```
[[1, 2] 
 [3, 4]]
```

- Output:
```
P: [[0., 1.]
    [1., 0.]]
L: [[1., 0.]
    [0.3, 1.]]
U: [[3., 4.]
    [0., 0.7]]
```

In [109]:
from scipy.linalg import lu

def perform_lu_decomposition(matrix):
    # YOUR CODE HERE
    P, L, U = lu(matrix)
    return np.round(P, decimals=1), np.round(L, decimals=1), np.round(U, decimals=1)
    raise NotImplementedError()

In [110]:
# testing with an example
perform_lu_decomposition(np.array([[1,2],[3,4]]))

(array([[0., 1.],
        [1., 0.]]),
 array([[1. , 0. ],
        [0.3, 1. ]]),
 array([[3. , 4. ],
        [0. , 0.7]]))

In [111]:
# grading cell 19
matrix = np.array([[2,  -1, -2], [-4,  6,  3], [-4,  -2,  8]])
permutation_matrix, lower_triangular_matrix, upper_triangular_matrix = perform_lu_decomposition(matrix)
assert np.trace(lower_triangular_matrix) == matrix.shape[0], "Permutation matrix is incorrect."

In [112]:
# grading cell 20
